import type { Metadata } from "next";
import "./globals.css";
import { InCartProvider } from "./ProductContext";
import { Josefin_Sans } from "next/font/google";
import { Playfair_Display } from "next/font/google";

const Josefin = Josefin_Sans({ subsets: ['latin'] });
const Playfair = Playfair_Display({subsets:['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Josefin.className}>
      <InCartProvider>
{children}
</InCartProvider>
</body>

    </html>
  );
}
